### ISSUE TITLE
Syslog parser fail with Juniper Logical System appname

### ISSUE THREAD

**Issue by renatoornelas** [FungusHumungus/syslog-loose#1]
Hi,

We use a feature called Logical System on Juniper Routers (basically a virtual router). When exporting syslog to vector, the app-name field isn't being parsed. The device sends the app-name as LOGICAL-SYSTEM-NAME:app-name (witch according to RFC 5424 is an valid app name).

Message parsed correctly:

Msg: 1 2020-05-22T14:59:10.908-03:00 OX-XXXX-MX204 rpd 6544 - - bgp_listen_accept: %DAEMON-4: Connection attempt from unconfigured neighbor: 2001:XXX:36::651d:0:1+34069

Message not parsed:

1 2020-05-22T14:59:09.250-03:00 OX-XXX-MX204 OX-XXX-CONTEUDO:rpd 6589 - - bgp_listen_accept: %DAEMON-4: Connection attempt from unconfigured neighbor: 2001:XXX::219:166+57284

So I don't get any fields when the log were generated inside a Logical System.

Regards,

**Comment by FungusHumungus** [comment]
@renatoornelas Sorry for the delay, it looks like my notifications weren't being forwarded to me correctly! I'll take a look.

**Comment by FungusHumungus** [comment]
@renatoornelas The message you posted above: 

> 1 2020-05-22T14:59:09.250-03:00 OX-XXX-MX204 OX-XXX-CONTEUDO:rpd 6589 - - bgp_listen_accept: %DAEMON-4: Connection attempt from unconfigured neighbor: 2001:XXX::219:166+57284

Have you missed off the facility and severity at the start of the message?

So should it really be something like: 

> <13>1 2020-05-22T14:59:09.250-03:00 OX-XXX-MX204 OX-XXX-CONTEUDO:rpd 6589 - - bgp_listen_accept: %DAEMON-4: Connection attempt from unconfigured neighbor: 2001:XXX::219:166+57284"

?

**Comment by renatoornelas** [comment]
I captured the text only via tcpdump, that's why it's missing from the text i send.

But i'm sure that both messages have the same facility/severity.

**Comment by FungusHumungus** [comment]
Great. If the message still doesn't parse properly after the fix is applied, feel free to file a separate issue.

**Comment by renatoornelas** [comment]
06:31:22.218765 IP XXXX.syslog > XXXX.syslog: SYSLOG daemon.warning, length: 150
E.......>.RS.[...[.Z........<28>1 2020-05-29T06:31:22.205-03:00 OX-XXXX-MX204 rpd 17751 - - bgp_listen_accept: Connection attempt from unconfigured neighbor: XXX+60365


06:31:22.864004 IP XXXX.syslog > XXXX.syslog: SYSLOG daemon.warning, length: 168
E.......>.Mc.[...[.Z.......(<28>1 2020-05-29T06:31:22.850-03:00 OX-XXXX-MX204 CLI-SPO1-XXX:rpd 17796 - - bgp_listen_accept: Connection attempt from unconfigured neighbor: 2001:XXX::XXX:197+8148

**Comment by FungusHumungus** [comment]
Perfect! The <28> was what I was looking for.
